# Generated by Django 5.1 on 2024-09-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="reserved_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("canceled", "Canceled"),
                ],
                default="reserved",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.CharField(default="def", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
